services:
  server_1:
    build: .
    restart: always
    container_name: server_1
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
