services:
  server_1:
    build: .
    restart: always
    container_name: server_1
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
  server_2:
    build: .
    restart: always
    container_name: server_2
    expose:
      - "3001"
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
  server_3:
    build: .
    restart: always
    container_name: server_3
    expose:
      - "3002"
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
  server_4:
    build: .
    restart: always
    container_name: server_4
    expose:
      - "3003"
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - PORT=3003
