services:
  development:
    image: ubuntu:latest
    container_name: development
    command: tail -F /dev/null
  server:
    build: .
    expose:
      - "80"
    ports:
      - "8000:80"
    container_name: server
